name: Build Onto

# Controls when the action will run. Triggers the workflow on push events but only
# for the master branch.
on:
  push:
    branches: [ master ]

jobs:
  build-ontology:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: pip install rdflib rdflib-jsonld

    - name: Merge ontology
      run: python ./scripts/build_ontology.py

    - name: Remove gitignore
      run: rm .gitignore
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # The folder the action should deploy.
